### ISSUE TITLE
建议用 umi 插件实现

### ISSUE THREAD

**Issue by xiaohuoni** [MudOnTire/antd-pro-page-tabs#1]
比如每个 route 都要加  wrappers: [RouteWatcher]
可以用插件来做这个事情。

**Comment by MudOnTire** [comment]
> 比如每个 route 都要加 wrappers: [RouteWatcher]
> 可以用插件来做这个事情。
好的，我研究一下

**Comment by MudOnTire** [comment]
> 比如每个 route 都要加 wrappers: [RouteWatcher]
> 可以用插件来做这个事情。

好的，我研究一下。
