### ISSUE TITLE
你好 请问如何集成到BasicLayout.tsx

### ISSUE THREAD

**Issue by CHENJKNB** [MudOnTire/antd-pro-page-tabs#2]
你好 请问如何集成到BasicLayout.tsx

**Comment by MudOnTire** [comment]
> 你好 请问如何集成到BasicLayout.tsx

你可以在BasicLayout里面把`chidlren`用 `TabLayout` 包一下试试。

**Comment by MudOnTire** [comment]
@chenjiakuan readme已更新，请查看。
