### ISSUE TITLE
能详细的讲一下如何集成到V5版本吗

### ISSUE THREAD

**Issue by joesdu** [MudOnTire/antd-pro-page-tabs#3]
能详细的讲一下如何集成到V5版本吗[官方最佳实践](https://github.com/ant-design/ant-design-pro)

**Comment by joesdu** [comment]
建议你能集成到官方的最佳实践中去,给他们整个PR

**Comment by MudOnTire** [comment]
> 能详细的讲一下如何集成到V5版本吗[官方最佳实践](https://github.com/ant-design/ant-design-pro)

哥，ant design pro有V5？我对他们生态还不太熟

**Comment by joesdu** [comment]
> > 能详细的讲一下如何集成到V5版本吗[官方最佳实践](https://github.com/ant-design/ant-design-pro)
> 
> 哥，ant design pro有V5？我对他们生态还不太熟

最佳实践有个V5的分支,虽然目前官方说是预览版,但是已经可以用于生产.我刚才试着把你这个库集成我公司的项目,发现你的tab都是按照整个页面的宽度在摆放.不能放到右边的内容区域.会超出到左侧的菜单栏.

**Comment by joesdu** [comment]
> > 能详细的讲一下如何集成到V5版本吗[官方最佳实践](https://github.com/ant-design/ant-design-pro)
> 
> 哥，ant design pro有V5？我对他们生态还不太熟

我刚觉我会了,我周末试试.

**Comment by joesdu** [comment]
试了下.还是存在一些问题.但是可以学习一下.

**Comment by MudOnTire** [comment]
@joesdu 嗯嗯，样式是有些问题。个人精力有限，有好的想法欢迎PR呀 😊。

**Comment by joesdu** [comment]
> @joesdu 嗯嗯，样式是有些问题。个人精力有限，有好的想法欢迎PR呀 😊。

以后有时间学习下,看看如何弄.

**Comment by pkaq** [comment]
v5 确实可以有
