### ISSUE TITLE
和新版本的pro-layout 有点不兼容

### ISSUE THREAD

**Issue by CHENJKNB** [MudOnTire/antd-pro-page-tabs#6]
和新版本的pro-layout 有点不兼容  能否修复一下bug 谢谢!

**Comment by dbxu** [comment]
兼容不了antd pro 的4X版本

**Comment by MudOnTire** [comment]
> 兼容不了antd pro 的4X版本

是样式有错乱嘛？

**Comment by dbxu** [comment]
> > 兼容不了antd pro的4X版本
> 
> 是样式有错乱嘛？

是的，我看你在tabs标签上加的style，是固定定位，页面一滚动就乱了，不滚动的情况下也是位置错乱

**Comment by Jerry-yx** [comment]
新版本的pro-layout是否有方案兼容呢？

**Comment by MudOnTire** [comment]
> 新版本的pro-layout是否有方案兼容呢？

antd5的？

**Comment by MudOnTire** [comment]
> > > 兼容不了antd pro的4X版本
> > 
> > 
> > 是样式有错乱嘛？
> 
> 是的，我看你在tabs标签上加的style，是固定定位，页面一滚动就乱了，不滚动的情况下也是位置错乱

要实现标签吸顶的效果目前除了固定定位没有特别好的方法，建议写样式覆盖取消吸顶，或者将其他固定定位元素的位置往下移动。

**Comment by MudOnTire** [comment]
@dbxu @chenjiakuan @yuanxuyan 请升级到0.2.3看看

**Comment by yuanxuyan** [comment]
升级后可以实现啦，挺不错的，唯一不足的一点 就是如下图如果点击面包屑的父级路由会重新刷新页面，tab页都没了
![image](https://user-images.githubusercontent.com/34082804/92712604-84f76c00-f38c-11ea-88ff-3cae803c1df6.png)

能否问一下是如何实现地呀？我最近也有写这个，用的antd tab页，然后再proLayout 里面获取到children 将children存储在一个列表内，根据列表渲染tabpane标签。但是不足的是每次切换tab标签的时候，页面都会重新刷新，不清楚是为什么，参考的github上的项目用的是umi2.0，他的是不会刷新的，我本地是3以上版本。

**Comment by Jerry-yx** [comment]
升级后可以实现啦，挺不错的，唯一不足的一点 就是如下图如果点击面包屑的父级路由会重新刷新页面，tab页都没了
![image](https://user-images.githubusercontent.com/34082804/92713242-54640200-f38d-11ea-90ee-4fa9d395997f.png)

能否问一下是如何实现地呀？我最近也有写这个，用的antd tab页，然后再proLayout 里面获取到children 将children存储在一个列表内，根据列表渲染tabpane标签。但是不足的是每次切换tab标签的时候，页面都会重新刷新，不清楚是为什么，参考的github上的项目用的是umi2.0，他的是不会刷新的，我本地是3以上版本。

**Comment by MudOnTire** [comment]
@Jerry-yx 和我的思路其实差不多，至于为什么页面会刷新需要排查具体是哪个组件刷新了。ant design 的 tabs 组件实现切换其实是把其他tab的内容 `display: none` 了，是不会导致页面刷新的。所以要看是不是上级组件有刷新。

我到没出现你说的点击面包屑页面刷新的情况，面包屑里面是用前端路由跳转的嘛？
